name: CI and CD

on:
  push:
    branches: [ main ]

jobs:
  ci-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: nodejs setup
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: |
         npm run install-deps
         npm run test
      - name: Building
        run: |
         mkdir dist
         echo "App built from commit: $GITHUB_SHA" > dist/app-version.txt
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: dist/

  cd-deploy-staging:
    runs-on: ubuntu-latest
    needs: ci-build-and-test

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: web-app
          path: dist/
      - name: deploy to staging env
        run: bash deploy.sh
